name: CI with Apptainer in Arch Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: apptainer/apptainer:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull Apptainer image
        run: apptainer pull ci-terra.sif oras://ghcr.io/simkinetic/ci-terra:latest
      - name: Run tests
        run: apptainer exec --bind $PWD:/app ci-terra.sif bash -c "cosm activate && . /app/.cosm/.env && terra test/testrunner.t --test"
      - name: Clean Apptainer cache
        run: apptainer cache clean
        if: always()